### ISSUE TITLE
Adding some instructions

### ISSUE THREAD

**Issue by iliaMonfared** [TylerEspo/ProcessInjector#1]
Hi,
after injecting the dll, how can we run a method inside our dll ?
and how about injecting exe into prcoess ?
thanks.

**Comment by TylerEspo** [comment]
You can only inject a DLL into a process not a exe. It creates another thread in the select process, from there you can can create hooks, overwrite memory, etc. I would read more here https://en.wikipedia.org/wiki/DLL_injection

**Comment by iliaMonfared** [comment]
but if you read the RunPE Codes, we can inject exe byte array into another
process in memory.
im so confused

**Comment by TylerEspo** [comment]
That is possible yes, but for ProcessInjector, we only accept dynamic link library files.
